name: EcosistemaPersonal
description: A new Flutter project.

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.2.1
  flutter_animate: 4.1.1+1
  from_css_color: 2.0.0
  go_router: 13.2.0
  google_fonts: ^4.0.3
  intl: ^0.18.0
  json_path: 0.7.1
  path_provider: 2.1.2
  path_provider_android: 2.2.2
  path_provider_foundation: ^2.3.0
  path_provider_platform_interface: ^2.1.0
  shared_preferences_android: 2.2.1
  shared_preferences_foundation: 2.3.5
  shared_preferences_platform_interface: 2.3.2
  shared_preferences_web: 2.3.0
  sqflite: ^2.2.6
  timeago: ^3.2.2
  url_launcher: ^6.1.10
  url_launcher_android: 6.3.0
  url_launcher_ios: 6.2.5
  url_launcher_platform_interface: 2.3.2
  flutterflow_ui: 0.2.0
  flutterflow_widgets: 0.0.52
  animations: ^2.0.11



dev_dependencies:
  flutter_lints: 3.0.1
  lints: 3.0.0

  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true
  assets:
    - assets/images/ 